### PR TITLE
Make the ISO with Hyper-V KVP Daemon

### PR DESCRIPTION
**Pull request by ailispaw**

### CODE REVIEW

**Comment by ailispaw** [comment]
@guyschaos
Could you test this ISO?
[barge-hyperv.iso.zip](https://github.com/bargees/barge-packer/files/849000/barge-hyperv.iso.zip)

**Comment by guyschaos** [comment]
@ailispaw 
Perfect! I love this one.
```bash
[bargee@barge ~]$ ps ax | grep kvp
  357 root     /usr/sbin/hv_kvp_daemon
[bargee@barge ~]$ lsmod
Module                  Size  Used by    Not tainted
xt_nat                  1536 18
veth                    3648  0
ipt_MASQUERADE           960 16
nf_nat_masquerade_ipv4     1412  1 ipt_MASQUERADE
xfrm_user              16512  1
iptable_nat             1280  4
nf_conntrack_ipv4       5248  6
nf_defrag_ipv4          1152  1 nf_conntrack_ipv4
nf_nat_ipv4             3266  1 iptable_nat
xt_addrtype             2240  7
xt_conntrack            2496  5
nf_nat                  9484  3 xt_nat,nf_nat_masquerade_ipv4,nf_nat_ipv4
nf_conntrack           48928  5 nf_nat_masquerade_ipv4,nf_conntrack_ipv4,nf_nat_ipv4,xt_conntrack,nf_nat
hv_balloon              9201  0 [permanent]
hv_utils               10916  1

```

One more thing, Hyper-V show me the address now.

ip

Only a little issue about the ssh welcome info:
```bash
Welcome to Barge 2.4.0, Docker version 17.03.0-ce, build 60ccb22
```
Thanks for your great job!

**Comment by ailispaw** [comment]
Hmm.
You have switched Docker to 17.03.0-ce on Barge 2.4.0.
It will be fixed by executing `sudo /etc/init.d/docker restart 17.03.0-ce` again on the current VM.

**Comment by ailispaw** [comment]
@guyschaos 
Thank you so much for your help again!!

I will release that ISO officially soon here.

**Comment by guyschaos** [comment]
My pleasure. Waiting for your release.    :D

**Comment by ailispaw** [comment]
Just released as v2.4.1.1, but the version of Barge OS is still 2.4.1 internally.
Thanks.

**Pull request merged**
